setopt PROMPT_SUBST

BOLD_RED='%F{red}%B'
BOLD_GREEN='%F{green}%B'
NORMAL='%f%b'
BOLD_BLUE='%F{blue}%B'
PROMPT_COL="%(?.${BOLD_BLUE}.${BOLD_RED})"
PROMPT_HOST="%(!.${BOLD_RED}%m${BOLD_BLUE}.${BOLD_GREEN}%n@%m${BOLD_BLUE})"

ZSH_THEME_GIT_PROMPT_PREFIX="("
ZSH_THEME_GIT_PROMPT_SUFFIX=") "
ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg_bold[green]%}"

PROMPT='${PROMPT_HOST} %1~${NORMAL} $(gitprompt)${PROMPT_COL}%#${NORMAL} '
